blogs/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blogs.apps import BlogsConfig
from blogs.views import (BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView,
                         BlogDeleteView)

app_name = BlogsConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='view'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('', include('mailings.urls', namespace='mailings')),
    path('users/', include('users.urls', namespace='users')),
    path('client/', include('clients.urls', namespace='client')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

mailings/urls.py
from django.urls import path
from mailings.apps import MailingsConfig
from mailings.views import (MailingParametersListView, MailingParametersCreateView, MailingParametersDetailsView,
                            MailingParametersDeleteView, MailingParametersUpdateView, MessageListView,
                            MessageCreateView,
                            MessageUpdateView, MessageDeleteView, LogsListView, index)

app_name = MailingsConfig.name

urlpatterns = [
    path('', index, name='index'),
    path('list/', MailingParametersListView.as_view(), name='list'),
    path('create/', MailingParametersCreateView.as_view(), name='create'),
    path('detail/<int:pk>', MailingParametersDetailsView.as_view(), name='detail'),
    path('update/<int:pk>', MailingParametersUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', MailingParametersDeleteView.as_view(), name='delete'),

    path('message_list/', MessageListView.as_view(), name='message_list'),
    path('message_create/', MessageCreateView.as_view(), name='message_create'),
    path('message_update/<int:pk>', MessageUpdateView.as_view(), name='message_update'),
    path('message_delete/<int:pk>', MessageDeleteView.as_view(), name='message_delete'),

    path('logs_list/', LogsListView.as_view(), name='logs_list'),
]

mailings/models.py
from django.db import models
from django.utils import timezone

from clients.models import Client
from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Message(models.Model):
    title = models.CharField(max_length=150, verbose_name='тема письма', **NULLABLE)
    content = models.TextField(verbose_name='содержание письма', **NULLABLE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='создатель', **NULLABLE)

    def __str__(self):
        return f'{self.title} {self.content}'

    class Meta:
        verbose_name = 'письмо'
        verbose_name_plural = 'письма'


class MailingParameters(models.Model):
    intervals = (
        ('per_day', 'раз в день'),
        ('per_week', 'раз в неделю'),
        ('per_month', 'раз в месяц')
    )
    status_variants = (
        ('not_active', 'не активна'),
        ('is_active', 'запущена'),
        ('finished', 'закончена успешно'),
        ('finished_date', 'закончена по сроку'),
        ('finished_error', 'законечена с ошибками')
    )
    title = models.CharField(
        max_length=150,
        verbose_name='название рассылки',
        default='mailing_no_name'
    )
    start_date = models.DateTimeField(
        default=timezone.now,
        verbose_name='дата начала рассылки'
    )
    end_date = models.DateTimeField(
        default=(timezone.now() + timezone.timedelta(days=1)),
        verbose_name='дата окончания рассылки'
    )
    next_date = models.DateTimeField(
        default=timezone.now,
        verbose_name='следующая дата рассылки'
    )
    interval = models.CharField(
        max_length=50,
        choices=intervals,
        default='per_day',
        verbose_name='интервал рассылки'
    )
    status = models.CharField(
        max_length=50,
        choices=status_variants,
        default='not_active',
        verbose_name='статус рассылки'
    )
    client = models.ManyToManyField(
        Client, verbose_name='Клиент'
    )
    message = models.ForeignKey(
        Message, verbose_name='Содержание письма',
        on_delete=models.CASCADE
    )
    owner = models.ForeignKey(
        User, verbose_name='Создатель',
        on_delete=models.CASCADE,
        **NULLABLE
    )

    def __str__(self):
        return (f'{self.title}: {self.start_date} - {self.end_date};'
                f'интервал: {self.interval};'
                f'статус: {self.status};'
                f'Создатель: {self.owner}')

    class Meta:
        verbose_name = 'параметры рассылки'
        verbose_name_plural = 'параметры рассылок'
        permissions = [
            ('deactivate_mailing', 'Can deactivate mailing'),
            ('view_all_mailings', 'Can view all mailings'),
        ]


class Logs(models.Model):
    mailing_parameters = models.ForeignKey(
        MailingParameters,
        verbose_name='Параметры рассылки',
        on_delete=models.CASCADE
    )
    date_time_mailing = models.DateTimeField(
        auto_now=True,
        verbose_name='дата и время последней рассылке',
        **NULLABLE
    )
    status_mailing = models.CharField(
        max_length=50,
        verbose_name='статус попытки',
        **NULLABLE
    )
    response = models.CharField(
        max_length=255,
        verbose_name='ответ почтового сервера',
        **NULLABLE
    )

    def __str__(self):
        return (f'Параметры сообщения: {self.mailing_parameters},'
                f'Отправлено: {self.date_time_mailing},'
                f'Статус: {self.status_mailing},'
                f'Ответ от постового сервера: {self.response}')

    class Meta:
        verbose_name = 'лог рассылки'
        verbose_name_plural = 'логи рассылок'

mailings/forms.py
from django.forms import ModelForm

from mailings.models import MailingParameters, Message


class MailingParametersForm(ModelForm):
    class Meta:
        model = MailingParameters
        exclude = ('owner', )


class MailingParametersManagerForm(ModelForm):
    class Meta:
        model = MailingParameters
        fields = ('status',)


class MessageForm(ModelForm):
    class Meta:
        model = Message
        exclude = ('owner',)

mailings/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from blogs.models import Blog
from clients.models import Client
from mailings.forms import MailingParametersForm, MailingParametersManagerForm, MessageForm
from mailings.models import MailingParameters, Message, Logs


class MailingParametersListView(LoginRequiredMixin, ListView):
    model = MailingParameters
    template_name = './mailings/mailingparameters_list.html'

    def get_queryset(self, qurester=None):
        queryset = super().get_queryset()
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name='manager'):
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class MailingParametersDetailsView(LoginRequiredMixin, DetailView):
    model = MailingParameters

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name='manager') and user != self.object.owner:
            raise PermissionDenied
        else:
            return self.object


class MailingParametersCreateView(LoginRequiredMixin, CreateView):
    model = MailingParameters
    form_class = MailingParametersForm
    success_url = reverse_lazy('mailings:list')

    def form_valid(self, form):
        mailing = form.save()
        mailing.owner = self.request.user
        mailing.save()
        return super().form_valid(form)


class MailingParametersUpdateView(LoginRequiredMixin, UpdateView):
    model = MailingParameters
    form_class = MailingParametersForm

    def get_success_url(self):
        return reverse('mailings:detail', args=[self.kwargs.get('pk')])

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            return MailingParametersForm
        if user.has_perm('mailings.deactivate_mailing'):
            return MailingParametersManagerForm
        raise PermissionDenied


class MailingParametersDeleteView(LoginRequiredMixin, DeleteView):
    model = MailingParameters
    success_url = reverse_lazy('mailings:list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class MessageListView(LoginRequiredMixin, ListView):
    model = Message

    def get_queryset(self, queryset=None):
        queryset = super().get_queryset()
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name='manager'):
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailings:create')

    def form_valid(self, form):
        message = form.save()
        message.sender = self.request.user
        message.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailings:message_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('mailings:message_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class LogsListView(LoginRequiredMixin, ListView):
    model = Logs


def index(request):
    count_mailing_items = MailingParameters.objects.count()
    count_active_mailing_items = MailingParameters.objects.filter(status='is_active').count()
    count_unic_clients = Client.objects.values_list('email', flat=True).count()
    random_blogs = Blog.objects.order_by('?')[:3]
    context = {'count_mailing_items': count_mailing_items,
               'count_active_mailing_items': count_active_mailing_items,
               'count_unic_clients': count_unic_clients,
               'random_blogs': random_blogs,
               }

    return render(request, 'mailings/index.html', context)

mailings/templates/mailings/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Сервис рассылок</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>


{% include 'mailings/includes/inc_mailing_menu.html' %}


<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Сервис рассылок</h1>
        </div>
    </section>
    {% block content %}
    {% endblock %}

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">

        </p>
        <p>&copy; 2024 - {% now 'Y' %}</p>

    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

mailings/templates/mailings/index.html
{% extends 'mailings/base.html' %}
{% load my_tags %}
<title>Сервис рассылок</title>
{% block content %}
<div class="col-12  mb-5">
    {% if user.is_authenticated %}
    <a class="btn btn-outline-primary" href="{% url 'mailings:create' %}">Создать рассылку</a>
    {% endif %}
</div>
<div class="album py-5 bg-light">
    <div class="container">
        <table class="table text-center">
            <tr>
                <th><h4>Количество рассылок</h4></th>
                <th><h4>Количество активных рассылок</h4></th>
                <th><h4>Количество уникальных клиентов</h4></th>
            </tr>
            <body>
            <tr>
                <td><h4>{{ count_mailing_items }}</h4></td>
                <td><h4>{{ count_active_mailing_items }}</h4></td>
                <td><h4>{{ count_unic_clients }}</h4></td>
            </tr>
            </body>
        </table>
        <div class="row">
            {% for object in random_blogs %}
            <div class="col-md-4">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">{{ object.title}}</h4>
                    </div>
                    <img src="{{ object.preview | media_filter }}">
                    <div class="card-body">

                        <ul class="list-unstyled mt-3 mb-4">

                            <li>Текст: {{ object.content }}</li>
                        </ul>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'blogs:view' object.pk %}" type="button"
                           class="w-100 btn btn-lg btn-outline-primary mb-3">Просмотр</a>
                    </div>

                </div>
            </div>

            {% endfor%}
        </div>
    </div>
</div>

{% endblock %}

mailings/templates/mailings/logs_list.html
{% extends 'mailings/base.html' %}
<title>Магазин</title>
{% block content %}
<h1 class="text-center">Попытки рассылки</h1>
<div class="album py-5 bg-light">
    <div class="container">

        <div class="row">
            {% for object in object_list %}
            <div class="col-md-5">
                <div class="card mb-5 box-shadow">
                    <div class="card-body">
                        <h4 class="my-0 fw-normal">{{ object.date_time_mailing }}</h4>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li>Статус: {{ object.status_mailing }}</li>
                        </ul>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li>Ответ сервера: {{ object.response }}</li>
                        </ul>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li>Рассылка: {{ object.mailing_parameters }}</li>
                        </ul>
                        <div class="d-flex justify-content-between align-items-center">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/mailingparameters_confirm_delete.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <p class="card-text">
                        <form method="post">
                            {% csrf_token %}
                            <p>
                                Хотите удалить эту рассылку "{{ object.title }}"?
                            </p>
                            <button type="submit" class="btn btn-primary">Подтвердить</button>
                            <a href="{% url 'mailings:list' %}" class="btn btn-warning">Отмена</a>
                        </form>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailings/templates/mailings/mailingparameters_detail.html
{% extends 'mailings/base.html' %}
{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <h4 class="my-0 fw-normal">{{ object.title }}</h4>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4">
                            <li>Начало: {{ object.start_date }}</li>
                            <li>Окончание: {{ object.end_date }}</li>
                            <li>Интервал: {{ object.interval }}</li>
                            <li>Следующая расылка: {{ object.next_date }}</li>
                            <li>Текст письма: {{ object.message.title }}</li>
                            <li>Содержимое письма: {{ object.message.content }}</li>
                            <li>Клиенты: {% for client in object.client.all %} {{client.email}} {% endfor %}</li>
                        </ul>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-sm btn-outline-secondary" href="{% url 'mailings:list' %}">Назад</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/mailingparameters_form.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

mailings/templates/mailings/mailingparameters_list.html
{% extends 'mailings/base.html' %}
<title>Сервис рассылок</title>
{% block content %}
<h1 class="text-center">Рассылки</h1>
<div class="col-12  mb-5">
    {% if user.is_authenticated %}
    <a class="btn btn-outline-primary" href="{% url 'mailings:create' %}">Создать рассылку</a>
    {% endif %}
</div>
<div class="album py-5 bg-light">
    <div class="container">

        <div class="row">
            {% for object in object_list %}
            <div class="col-md-5">
                <div class="card mb-5 box-shadow">
                    <div class="card-body">
                        <h4 class="my-0 fw-normal">{{ object.title }}</h4>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li>Начало: {{ object.start_date }}</li>
                            <li>Окончание: {{ object.end_date }}</li>
                            <li>Интервал: {{ object.interval }}</li>
                            <li>Статус расылки: {{ object.status }}</li>
                            <li>Следующая расылка: {{ object.next_date }}</li>
                        </ul>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-sm btn-outline-secondary" href="{% url 'mailings:detail' object.pk %}">
                                    Просмотр
                                </a>

                                <a class="btn btn-sm btn-outline-secondary" href="{% url 'mailings:update' object.pk %}">
                                    Редактировать
                                </a>
                                <a class="btn btn-sm btn-outline-secondary" href="{% url 'mailings:delete' object.pk %}">
                                    Удалить
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/message_confirm_delete.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <p class="card-text">
                        <form method="post">
                            {% csrf_token %}
                            <p>
                                Хотите удалить это сообщение "{{ object.title }}"?
                            </p>
                            <button type="submit" class="btn btn-primary">Подтвердить</button>
                            <a href="{% url 'mailings:list' %}" class="btn btn-warning">Отмена</a>
                        </form>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailings/templates/mailings/message_form.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

mailings/templates/mailings/message_list.html
{% extends 'mailings/base.html' %}
<title>Магазин</title>
{% block content %}
<h1 class="text-center">Сообщения</h1>
<div class="col-12  mb-5">
    {% if user.is_authenticated %}
    <a class="btn btn-outline-primary" href="{% url 'mailings:message_create' %}">Создать сообщение</a>
    {% endif %}
</div>
<div class="album py-5 bg-light">
    <div class="container">

        <div class="row">
            {% for object in object_list %}
            <div class="col-md-5">
                <div class="card mb-5 box-shadow">
                    <div class="card-body">
                        <h4 class="my-0 fw-normal">{{ object.title }}</h4>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li>Текст сообщения: {{ object.content }}</li>

                        </ul>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-sm btn-outline-secondary"
                                   href="{% url 'mailings:message_update' object.pk %}">
                                    Редактировать
                                </a>
                                <a class="btn btn-sm btn-outline-secondary"
                                   href="{% url 'mailings:message_delete' object.pk %}">
                                    Удалить
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}