blogs/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blogs.apps import BlogsConfig
from blogs.views import (BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView,
                         BlogDeleteView)

app_name = BlogsConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='view'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('', include('mailings.urls', namespace='mailings')),
    path('users/', include('users.urls', namespace='users')),
    path('client/', include('clients.urls', namespace='client')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

blogs/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Наименование')
    content = models.TextField(verbose_name='Текст статьи')
    preview = models.ImageField(upload_to='blogs/photo', verbose_name='Изображение', **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    country = models.IntegerField(default=0, verbose_name='Просмотры')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Статья блога'
        verbose_name_plural = 'Статьи блога'

blogs/forms.py
from django import forms

from blogs.models import Blog


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if not isinstance(field.widget, forms.CheckboxInput):
                field.widget.attrs['class'] = 'form-control'


class BlogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        exclude = ('country',)

blogs/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blogs.forms import BlogForm
from blogs.models import Blog
from blogs.services import get_articles_from_cache


class BlogCreateView(PermissionRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blogs:list')
    permission_required = 'blogs.add_blog'

    def form_valid(self, form):
        if form.is_valid():
            form.save()
        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog

    def get_queryset(self):
        queryset = get_articles_from_cache().filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.country += 1
        self.object.save()
        return self.object


class BlogUpdateView(PermissionRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogForm
    permission_required = 'blogs.change_blog'

    def get_success_url(self):
        return reverse('blogs:detail', args=[self.kwargs.get('pk')])


class BlogDeleteView(PermissionRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blogs:list')
    permission_required = 'blogs.delete_blog'

blogs/templates/blogs/blog_confirm_delete.html
{% extends 'store/base.html' %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <p class="card-text">
                        <form method="post">
                            {% csrf_token %}
                            <p>
                                Хотите удалить блог "{{ object.title }}"?
                            </p>
                            <button type="submit" class="btn btn-primary">Подтвердить</button>
                            <a href="{% url 'blogs:list' %}" class="btn btn-warning">Отмена</a>
                        </form>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blogs/templates/blogs/blog_detail.html
{% extends 'mailings/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="card mb-6 box-shadow">
                    <img src="{{ object.preview | media_filter }}">
                    <div class="card-body">
                        <p class="card-text">
                        <h2>{{ object.title}}</h2>
                        <p class="card-text">Содержание: {{ object.content }}</p>

                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-sm btn-primary"
                                   href="{% url 'blogs:list' %}">Назад</a>
                            </div>
                            <small class="text-muted">{{ object.created_at }}</small>
                        </div>
                    </div>
                    <div class="card-footer">
                        Просмотры: {{ object.country }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blogs/templates/blogs/blog_form.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <div class="card-header">
                            {% if object %}
                            <h5 class="card-title">Редактирование статьи</h5>
                            {% else %}
                            <h5 class="card-title">Добавление статьи</h5>
                            {% endif %}
                        </div>
                        <p class="card-text">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>
                        </form>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blogs/templates/blogs/blog_list.html
{% extends 'mailings/base.html' %}
{% load my_tags %}
{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Блог</h1>
    </div>
</section>
<div class="col-12  mb-5">
    {% if perms.blogs.add_blogarticle %}
    <a class="btn btn-outline-primary" href="{% url 'blogs:create' %}">Создать блог</a>
    {% endif %}
</div>
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for object in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <div class="card-title">
                            Блог "{{ object.title }}"
                        </div>
                    </div>
                    <img src="{{ object.preview | media_filter }}" />
                    <div class="card-body">
                        <p class="card-text">
                            {{ object.content | truncatechars:100 }}<br>


                        </p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-sm btn-outline-secondary"
                                   href="{% url 'blogs:view' object.pk %}">Просмотр</a>
                                {% if perms.blogs.change_blogarticle %}
                                <a class="btn btn-sm btn-outline-secondary"
                                   href="{% url 'blogs:edit' object.pk %}">Редактировать</a>
                                {% endif %}
                                {% if perms.blogs.delete_blogarticle %}
                                <a class="btn btn-sm btn-outline-secondary"
                                   href="{% url 'blogs:delete' object.pk %}">Удалить</a>
                                {% endif %}
                            </div>

                        </div>
                        <small class="text-muted">{{ object.created_at }}</small><br>

                        <small class="text-muted">Просмотры: {{ object.country }}</small>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}