blogs/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blogs.apps import BlogsConfig
from blogs.views import (BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView,
                         BlogDeleteView)

app_name = BlogsConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='view'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('', include('mailings.urls', namespace='mailings')),
    path('users/', include('users.urls', namespace='users')),
    path('client/', include('clients.urls', namespace='client')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, ProfileView, RegisterMessageView, PasswordRecoveryView, \
    PasswordRecoveryMessageView, UserListView, toggle_activity

app_name = UsersConfig.name


urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email_confirm/<str:token>/', email_verification, name='email_confirm'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('users_list/', UserListView.as_view(), name='list'),
    path('register/message/', RegisterMessageView.as_view(), name='register_message'),
    path('password_recovery/', PasswordRecoveryView.as_view(), name='password_recovery'),
    path('password_recovery_message/', PasswordRecoveryMessageView.as_view(), name='recovery_message'),
    path('toggle_activity/<int:pk>/', toggle_activity, name='toggle_activity'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {"blank": True, "null": True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/avatars/', verbose_name='аватар', **NULLABLE)
    token = models.CharField(max_length=100, verbose_name='токен', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'
        permissions = [
            ('set_active', 'Activate/deactivate user'),
            ('view_all_users', 'Can view all users'),
        ]


    def __str__(self):
        return f"{self.email}"

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import BooleanField

from users.models import User


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, fild in self.fields.items():
            if isinstance(fild, BooleanField):
                fild.widget.attrs['class'] = 'form-check-input'
            else:
                fild.widget.attrs['class'] = 'form-control'


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ("email", "password1", "password2")


class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'phone', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()


class ManagerUserForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('is_active',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()


class PasswordRecoveryForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ('email',)

users/views.py
import secrets

from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, TemplateView, ListView
from config.settings import EMAIL_HOST_USER
from users.forms import UserRegisterForm, PasswordRecoveryForm, UserProfileForm
from users.models import User


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:register_message')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email_confirm/{token}/'
        send_mail(
            subject='Подтверждение почты',
            message=f'Для подтверждения почты перейдите по ссылке: {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return HttpResponseRedirect('/users/login/')


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserListView(PermissionRequiredMixin, ListView):
    model = User
    permission_required = ('users.view_all_users', 'users.set_active')


class RegisterMessageView(TemplateView):
    # model = User
    template_name = 'users/register_message.html'


class PasswordRecoveryMessageView(TemplateView):
    template_name = 'users/password_recovery_message.html'


class PasswordRecoveryView(TemplateView):
    model = User
    template_name = 'users/password_recovery_form.html'
    form_class = PasswordRecoveryForm
    success_url = reverse_lazy('users:recovery_message')

    def post(self, request, *args, **kwargs):
        email = request.POST.get('email')
        user = User.objects.get(email=email)
        token = secrets.token_hex(10)
        user.set_password(token)
        user.save()

        host = self.request.get_host()
        url = f'http://{host}/users/login/'

        send_mail(
            'Восстановление пароля',
            f'Ваш новый пароль {token}, перейдите по ссылке {url}',
            EMAIL_HOST_USER,
            [user.email]
        )
        return HttpResponseRedirect('/users/password_recovery_message/')


@permission_required('users.set_active')
def toggle_activity(request, pk):
    user = User.objects.get(pk=pk)
    if user.is_active:
        user.is_active = False
    else:
        user.is_active = True
    user.save()
    return redirect(reverse('users:users_list'))

users/templates/users/login.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                        <h3 class="card-title">
                            Вход
                        </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Войти</button>
                    <a class="p-l-2 btn btn-primary" href="{% url 'users:password_recovery' %}">Восстановить пароль</a>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/password_recovery_form.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                        <h3 class="card-title">
                            Введите email для отправки нового пароля
                        </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                        <label class="form-label">Email</label>
                        <input type="email" name="email" class="form-control">
                    <button type="submit" class="btn btn-primary">Отправить</button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/password_recovery_message.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="container">
    <div class="row text-center">
        <h2>На указанную почту отправлено сообщение с новым паролем.</h2>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                        <h3 class="card-title">
                            Регистрация
                        </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Регистрация</button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/register_message.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="container">
    <div class="row text-center">
        <h2>На указанную почту отправлено сообщение с ссылкой о подтверждении почты</h2>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                        <h3 class="card-title">
                            Профиль
                        </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'mailings/base.html' %}
<title>Список пользователей</title>
{% block content %}
<h1 class="text-center">Список пользователей</h1>
<div class="col-12  mb-5">
</div>
<div class="album py-5 bg-light">
    <div class="container">

        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">Email</th>
                <th scope="col">Статус</th>
                <th scope="col">Персонал</th>
                <th scope="col">Изменение сатуса</th>
            </tr>
            </thead>
            <tbody>
            {% for user in object_list %}
            <tr>
                <td>{{ user.email }}</td>
                <td>{{ user.is_active }}</td>
                <td>{{ user.is_staff }}</td>
                <td>{% if perms.users.set_active %}
                    {% if user.is_active %}
                    <a href="{% url 'users:toggle_activity' user.pk %}"
                       class="btn btn-sm btn-outline-danger">Деактивировать</a>
                    {% else %}
                    <a href="{% url 'users:toggle_activity' user.pk %}"
                       class="btn btn-sm btn-outline-success">Активировать</a>
                    {% endif %}
                    {% endif %}
                </td>

            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}